<a href="https://colab.research.google.com/github/purendra25/ds/blob/master/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Importing the dataset

In [ ]:
dataset = pd.read_csv("Data.csv")
# print(dataset)

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)

#  print(X)
# print(y)
#X = dataset.iloc[]

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Taking care of missing data

In [ ]:
from sklearn.impute import  SimpleImputer
sk = SimpleImputer(missing_values=np.nan, strategy='mean' )
sk.fit(X[:,1:3])
X[:,1:3] = sk.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])],remainder = 'passthrough' )
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)  
print(y)


[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state = 1)

print(X_train)
# print(X_test)
# print(y_train)
# print(y_test)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
 print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [ ]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578554 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414833 -0.014117293757057846
  -0.07013167641635404]
 [0.0 1.0 0.0 -0.7745966692414833 0.5667085065333239 0.6335624327104546]
 [1.0 0.0 0.0 1.2909944487358056 -0.3045301939022487 -0.307866172742979]
 [1.0 0.0 0.0 1.2909944487358056 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 -0.7745966692414833 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414833 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7745966692414833 -0.7401495441200352 -0.5646194287757336]]


In [ ]:
print(X_test)

[[1.0 0.0 1.0 -1.1102230246251565e-16 -1.0 -1.0]
 [0.0 1.0 0.0 -1.1102230246251565e-16 1.0 1.0]]
